// Copyright (C) 2022 Davide Peressoni
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

use proc_macro::TokenStream;
use quote::{format_ident, quote};
use syn::{parse_quote, Meta};

/// Extract type name (last path segment) from a type for use in generated names.
fn type_to_ident(ty: &syn::Type) -> syn::Ident {
    match ty {
        syn::Type::Path(p) => p
            .path
            .segments
            .last()
            .map(|s| s.ident.clone())
            .unwrap_or_else(|| format_ident!("Opt")),
        _ => format_ident!("Opt"),
    }
}

/// Parse `group_prefix = "Literal"` from `#[clap_serde(...)]` attribute.
fn parse_group_prefix(attr: &syn::Attribute) -> Option<String> {
    attr.parse_args::<Meta>().ok().and_then(|meta| {
        if let Meta::NameValue(nv) = meta {
            if nv.path.is_ident("group_prefix") {
                if let syn::Lit::Str(s) = &nv.lit {
                    return Some(s.value());
                }
            }
        }
        None
    })
}

/// Enables clap and serde derive on the following struct.
///
/// It will automatically implement also the `ClapSerde` and [`Default`] traits.  
/// Use `#[default(value)]` attribute to change the default value of a field.  
/// Use `#[clap_serde]` attribute on the fields which type is a struct generated by this macro
/// (recursive behaviour).
/// Use `#[clap_serde(group_prefix = "Name")]` to give a unique Opt type name for that field,
/// so the same struct type can be used in multiple flattened fields without name collision.
///
/// This derive macro generates a struct (`ClapSerde::Opt`) with the same fields of the original,
/// but which types are wrapped in [`Option`].  
/// Such structure can be parsed from command line with clap and from any serde Deserializer.
/// It can also be merged to the original struct: only the not-`None` fields will be used to update
/// it. See `ClapSerde::update` and `ClapSerde::merge`.
#[proc_macro_derive(
    ClapSerde,
    attributes(clap, structopt, command, arg, group, serde, default, clap_serde)
)]
pub fn clap_serde(item: TokenStream) -> TokenStream {
    // AST of the struct on which this derive proc macro is applied.
    // It will be modified to generate the corresponding Opt.
    let mut ast: syn::DeriveInput = syn::parse(item).unwrap();

    let mut no_fields = syn::punctuated::Punctuated::new();

    // Get a mutable reference to the fields.
    let fields = match &mut ast.data {
        syn::Data::Struct(data) => match &mut data.fields {
            syn::Fields::Named(fields) => &mut fields.named,
            syn::Fields::Unit => &mut no_fields,
            _ => panic!("clap supports only non-tuple structs"),
        },
        syn::Data::Enum(_) => panic!("ClapSerde currently supports only structs"),
        _ => panic!("clap supports only structs and enums"),
    };

    // Get the name of the struct and generate name for the corresponding Opt
    let name = ast.ident;
    ast.ident = format_ident!("ClapSerdeOptional{}", name);
    let opt_name = &ast.ident;
    let default_doc = format!("Create default {}", name);

    // Get generics for trait implementation
    let (impl_generics, ty_generics, where_clause) = ast.generics.split_for_impl();

    let field_names: Vec<_> = fields.iter().map(|f| f.ident.clone().unwrap()).collect();

    // Recursive: (field_ident, use_wrapper) where use_wrapper = true means update via .0
    let mut recursive_fields = Vec::new();
    let mut not_recursive_fields = Vec::new();
    let mut wrapper_defs: Vec<(syn::Ident, syn::Type)> = Vec::new();

    let default_values: Vec<_> = fields
        .iter_mut()
        .map(|f| {
            let ty = f.ty.clone();
            let ty_ident = type_to_ident(&ty);

            let mut def_val = parse_quote!(<#ty as core::default::Default>::default());
            let mut not_recursive = true;
            let mut group_prefix: Option<String> = None;

            f.attrs.retain(|attr| {
                if attr.path.is_ident(&format_ident!("default")) {
                    def_val = attr.tokens.clone();
                    false
                } else if attr.path.is_ident(&format_ident!("clap_serde")) {
                    not_recursive = false;
                    group_prefix = parse_group_prefix(attr);
                    false
                } else {
                    true
                }
            });

            if not_recursive {
                not_recursive_fields.push(f.ident.clone());
            } else {
                if let Some(prefix) = &group_prefix {
                    let wrapper_name = format_ident!("ClapSerdeOptional{}{}", prefix, ty_ident);
                    wrapper_defs.push((wrapper_name.clone(), ty.clone()));
                    f.ty = parse_quote!(#wrapper_name);
                } else {
                    f.ty = parse_quote!(<#ty as clap_serde_derive2::ClapSerde>::Opt);
                }
                recursive_fields.push((f.ident.clone(), group_prefix.is_some()));
            }

            let ft = &f.ty;
            f.ty = parse_quote!(Option<#ft>);

            def_val
        })
        .collect();

    let wrapper_structs = wrapper_defs.iter().map(|(wrapper_name, inner_ty)| {
        let inner_opt: syn::Type = parse_quote!(<#inner_ty as clap_serde_derive2::ClapSerde>::Opt);
        quote! {
            #[doc(hidden)]
            #[derive(clap::Parser, serde::Deserialize, core::default::Default)]
            #[serde(transparent)]
            pub struct #wrapper_name(
                #[command(flatten)]
                pub #inner_opt
            );
        }
    });

    let update_recursive = recursive_fields.iter().map(|(fid, use_wrapper)| {
        if *use_wrapper {
            quote! {
                if let core::option::Option::Some(mut v) = other.#fid.take() {
                    self.#fid.update(core::borrow::BorrowMut::borrow_mut(&mut v.0));
                }
            }
        } else {
            quote! {
                if let core::option::Option::Some(mut v) = other.#fid.take() {
                    self.#fid.update(&mut v);
                }
            }
        }
    });

    quote! {
        #(#wrapper_structs)*

        #[doc(hidden)]
        #[derive(clap::Parser, serde::Deserialize, core::default::Default)]
        #ast

        impl #impl_generics clap_serde_derive2::ClapSerde for #name #ty_generics
            #where_clause
        {
            type Opt = #opt_name;

            fn update(&mut self, mut other: impl core::borrow::BorrowMut<Self::Opt>) {
                let other = other.borrow_mut();
                #(
                    if let core::option::Option::Some(v) = other.#not_recursive_fields.take() {
                        self.#not_recursive_fields = v;
                    }
                )*
                #(#update_recursive)*
            }
        }

        impl #impl_generics core::default::Default for #name #ty_generics #where_clause {
            #[doc = #default_doc]
            fn default() -> Self {
                Self {
                    #(
                        #field_names: #default_values,
                    )*
                }
            }
        }

        impl #impl_generics core::convert::From<<Self as clap_serde_derive2::ClapSerde>::Opt>
            for #name #ty_generics #where_clause
        {
            fn from(data: <Self as clap_serde_derive2::ClapSerde>::Opt) -> Self {
                Self::default().merge(data)
            }
        }
        impl #impl_generics core::convert::From<&mut <Self as clap_serde_derive2::ClapSerde>::Opt>
            for #name #ty_generics #where_clause
        {
            fn from(data: &mut <Self as clap_serde_derive2::ClapSerde>::Opt) -> Self {
                Self::default().merge(data)
            }
        }
    }
    .into()
}
